#if !canImport(ObjectiveC)
import XCTest

extension BNSConnectionInternalStateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BNSConnectionInternalStateTests = [
        ("testConnectionResetAfterCancelled", testConnectionResetAfterCancelled),
        ("testIdleTimeoutAfterCancelled", testIdleTimeoutAfterCancelled),
        ("testImmediateCancelled", testImmediateCancelled),
        ("testImmediateFailed", testImmediateFailed),
        ("testIOErrorAfterCancelled", testIOErrorAfterCancelled),
        ("testMultipleFailureTransitions", testMultipleFailureTransitions),
        ("testNormalTransition", testNormalTransition),
    ]
}

extension BNSHTTP1ConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BNSHTTP1ConnectionTests = [
        ("testCancelImmediately", testCancelImmediately),
        ("testStartThenCancel", testStartThenCancel),
        ("testStartThenConnectionUpgradedThenCancelled", testStartThenConnectionUpgradedThenCancelled),
    ]
}

extension BNSHTTP2ConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BNSHTTP2ConnectionTests = [
        ("testCancelImmediately", testCancelImmediately),
        ("testStartThenCancel", testStartThenCancel),
    ]
}

extension BNSWebSocketConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BNSWebSocketConnectionTests = [
        ("testCancelImmediately", testCancelImmediately),
        ("testStartThenCancel", testStartThenCancel),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BNSConnectionInternalStateTests.__allTests__BNSConnectionInternalStateTests),
        testCase(BNSHTTP1ConnectionTests.__allTests__BNSHTTP1ConnectionTests),
        testCase(BNSHTTP2ConnectionTests.__allTests__BNSHTTP2ConnectionTests),
        testCase(BNSWebSocketConnectionTests.__allTests__BNSWebSocketConnectionTests),
    ]
}
#endif
